### ISSUE TITLE
usbreset does not properly reset 8dev_2100 dongle

### ISSUE THREAD

**Issue by GiedriusM** [8devices/pi-gen#4]
Usbreset should completely power down the 8dev_dongle, however only a slight/short voltage drop is observed and in some cases it's impossible to reset the device if it hangs. This might be due to capacitors on 8dev_2100, which are not fully discharged during short power down. Power off duration should be increased.

**Comment by Lycopersicum** [comment]
usbreset doesn't perform the required functionality, therefore it's changed to "_uhubctl_" #5 . Voltage drop on capacitors reaches 50mV and less (fully discharged) with this command:
`sudo uhubctl -p $( sudo uhubctl|grep 257f:0002|awk '{print($2)}'|sed 's/://' ) -a 2`

If problem reoccurs in future - time between shutting down and powering port back on could be changed easily:
`sudo uhubctl -p $( sudo uhubctl|grep 257f:0002|awk '{print($2)}'|sed 's/://' ) -a 2 -d <duration(seconds)>`
